apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: cluster-proxy
imagePullSecrets:
 {{- range .Values.proxyAgentImagePullSecrets }}
- name: {{ . }}
 {{- end }}
